### ISSUE TITLE
New build from scratch getting /etc/one-context.d/60-grow-fs: line 25: [: 6141.88: integer expression expected

### ISSUE THREAD

**Issue by vizonyc** [jirutka/one-context#2]
Last hurdle, can you tell me where I might have messed up?

**Comment by jirutka** [comment]
It seems that the script failed to get size of your FS or device, don’t know why. I’ve fixed the grow-fs script to not fail in this condition (comparing nothing with nothing or number) and print warning instead.

**Comment by vizonyc** [comment]
hmm how is it getting local dev_path="$1"?

**Comment by jirutka** [comment]
[scripts/grow-fs:45](https://github.com/jirutka/one-context/blob/12270733207158f1c5b649696d386a8b23655d13/scripts/grow-fs#L45)
