### ISSUE TITLE
/60-grow-fs: line 25: [: 9214.98: integer expression expected

### ISSUE THREAD

**Issue by ghost** [jirutka/one-context#4]
Hello @jirutka 

Sorry to bother you again but i ran in to this:
```
/60-grow-fs: line 25: [: 9214.98: integer expression expected
```

Seems the .98 came unexpected. I was able to solve this by adding a 
```
| sed 's/\.[^.]*$//')
```
to the local fs_size array.

thanks and cheers

**Comment by jirutka** [comment]
Thanks for the report, I’ve fixed it in master.
