### ISSUE TITLE
Setting hostname does not work

### ISSUE THREAD

**Issue by BernhardGruen** [jirutka/one-context#5]
Setting the Hostname with the environment variable SET_HOSTNAME does not work for me.
It seems the script writes the hostname into /etc/conf.d/hostname .
But this file is not used in Alpine Linux. Instead /etc/hostname is always used.

Possible workaround/solution:
Write to /etc/hostname too.

**Comment by jirutka** [comment]
It also executes `hostname` ([scripts/hostname:7](https://github.com/jirutka/one-context/blob/master/scripts/hostname#L7)). I think that the problem is elsewhere. I have `SET_HOSTNAME = "$NAME"` in my ONe template. IIRC I copied this from the original one-context scripts.
